# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='icon',
        ),
    ]
