# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20170610_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, help_text='HTML url for repository', null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='budget.Project'),
        ),
    ]
