# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20171117_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='run_date',
            field=models.DateTimeField(blank=True, help_text='Estimated.', null=True),
        ),
    ]
