# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:28
from __future__ import unicode_literals

import budget.models.column
import budget.models.project
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20171125_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slack_channel',
            field=models.CharField(blank=True, help_text='A channel to notify with activity, e.g., #my-channel.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=budget.models.column.Column.get_default_board, on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='budget.Board'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=budget.models.project.Project.get_default_column, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='budget.Column'),
        ),
    ]
