export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_COLUMN = 'CREATE_COLUMN';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const CREATE_TODO = 'CREATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_NOTES = 'UPDATE_NOTES';

export const SET_NOTE = 'SET_NOTE';
export const OPEN_NOTE = 'OPEN_NOTE';
export const CLOSE_NOTE = 'CLOSE_NOTE';

export const API_SENDING = 'API_SENDING';
export const API_SUCCESS = 'API_SUCCESS';
export const API_ERROR = 'API_ERROR';
export const API_RESET = 'API_RESET';

export const CREATE_USER = 'CREATE_USER';
export const ADD_REPORTER = 'ADD_REPORTER';
export const REMOVE_REPORTER = 'REMOVE_REPORTER';
export const ADD_EDITOR = 'ADD_EDITOR';
export const REMOVE_EDITOR = 'REMOVE_EDITOR';
export const ADD_DEVELOPER = 'ADD_DEVELOPER';
export const REMOVE_DEVELOPER = 'REMOVE_DEVELOPER';

export const CREATE_TAG = 'CREATE_TAG';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';

export const CREATE_TYPE = 'CREATE_TYPE';
export const ADD_TYPE = 'ADD_TYPE';
export const REMOVE_TYPE = 'REMOVE_TYPE';

export const ADD_FILTER_DEVELOPER = 'ADD_FILTER_DEVELOPER';
export const REMOVE_FILTER_DEVELOPER = 'REMOVE_FILTER_DEVELOPER';
export const ADD_FILTER_TYPE = 'ADD_FILTER_TYPE';
export const REMOVE_FILTER_TYPE = 'REMOVE_FILTER_TYPE';
export const SET_FILTER_DATE_RANGE = 'SET_FILTER_DATE_RANGE';
export const RESET_FILTERS = 'RESET_FILTERS';
